spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/checkout_db
    username: checkout_user
    password: checkout_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    baseline-on-migrate: true
  
  security:
    user:
      name: admin
      password: admin

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
    url: /v3/api-docs
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
  show-actuator: false
  packages-to-scan: Altech.checkout.controller
  pathsToMatch: /**

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    Altech.checkout: DEBUG 